version: '3'
services:
  nginx:
    image: 'bitnami/nginx:1.16'
    ports:
      - '80:8080'
    volumes:
      - './nginx/nginx.conf:/etc/nginx/nginx.conf:ro'
      - './nginx/nginx.d/:/etc/nginx/nginx.d/'
      - './data/www/:/app/'

  test-endpoint:
    image: 'bitnami/nginx:1.16'
    ports:
      - '4001:8080'
