version: '3'
services:
  nginx:
    image: 'bitnami/nginx:1.16'
    ports:
      - '80:8080'
    volumes:
      - './nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro'
      - './nginx/config/nginx.d/:/etc/nginx/nginx.d/'
      - './nginx/data/www/:/app/'

  test-endpoint:
    image: 'bitnami/nginx:1.16'
    ports:
      - '4001:8080'
    volumes:
      - './test-endpoint/config/nginx.conf:/etc/nginx/nginx.conf:ro'
      - './test-endpoint/config/nginx.d/:/etc/nginx/nginx.d/'
      - './test-endpoint/data/www/:/app/'
